### ISSUE TITLE
Create A Firefox Addon

### ISSUE THREAD

**Issue by thealphadollar** [CodeStash-KGP/Savitar#1]
Using the same concept and code as the module, we can develop an addon for
firefox.

**Comment by kaustubhhiware** [comment]
There are addons in firefox which allow to install chrome extensions in firefox. Have a look at [foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/), you will need to ensure your extension is compatible with it.

**Comment by thealphadollar** [comment]
Thanks, I'll look into this :D Probably it requires the app to be in Chrome web store which currently I haven't done. If I see the need, I'll do it.

**Comment by Vipul999ujawane** [comment]
Firefox now supports WebExtensions, so you don't need to code this again. But you need to have get it signed by Firefox and in the store. This [https://developer.mozilla.org/en-US/Add-ons/Distribution](url) might help.

**Comment by thealphadollar** [comment]
Fixed in #6
